# Pandas

# Introduction

In [ ]:
#Pandas is a library written for the python programming language for data manipulation and analysis. In particular,
#it offers data structures and operations for manipulating numerical tables.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('weather.csv')#reading csv file
df  #printing dataset

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# functions

In [78]:
df.columns  #gives name of columns

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [79]:
df.dtypes   #gives datatypes of all columns

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [80]:
df.index   #gives the starting and endng index of rows

RangeIndex(start=0, stop=366, step=1)

In [81]:
df.count()  #gives the nmber of non null values

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

In [82]:
df.info()   #gives information about data types and non null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

In [83]:
df.describe()  #tells about count,mean and median etc

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustSpeed,WindSpeed9am,WindSpeed3pm,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RISK_MM
count,366.000000,366.000000,366.000000,366.000000,363.000000,364.000000,359.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000,366.000000
mean,7.265574,20.550273,1.428415,4.521858,7.909366,39.840659,9.651811,17.986339,72.035519,44.519126,1019.709016,1016.810383,3.890710,4.024590,12.358470,19.230874,1.428415
std,6.025800,6.690516,4.225800,2.669383,3.481517,13.059807,7.951929,8.856997,13.137058,16.850947,6.686212,6.469422,2.956131,2.666268,5.630832,6.640346,4.225800
min,-5.300000,7.600000,0.000000,0.200000,0.000000,13.000000,0.000000,0.000000,36.000000,13.000000,996.500000,996.800000,0.000000,0.000000,0.100000,5.100000,0.000000
25%,2.300000,15.025000,0.000000,2.200000,5.950000,31.000000,6.000000,11.000000,64.000000,32.250000,1015.350000,1012.800000,1.000000,1.000000,7.625000,14.150000,0.000000
50%,7.450000,19.650000,0.000000,4.200000,8.600000,39.000000,7.000000,17.000000,72.000000,43.000000,1020.150000,1017.400000,3.500000,4.000000,12.550000,18.550000,0.000000
75%,12.500000,25.500000,0.200000,6.400000,10.500000,46.000000,13.000000,24.000000,81.000000,55.000000,1024.475000,1021.475000,7.000000,7.000000,17.000000,24.000000,0.200000
max,20.900000,35.800000,39.800000,13.800000,13.600000,98.000000,41.000000,52.000000,99.000000,96.000000,1035.700000,1033.200000,8.000000,8.000000,24.700000,34.500000,39.800000

In [5]:
df.head()  #gives n number of values from top

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

In [85]:
df.tail(10) #gives n number of values from bottom

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
356,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,35.0,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,26.0,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
358,0.9,20.7,0.0,5.4,8.4,NNW,39.0,SSE,N,2.0,...,29,1023.2,1018.4,3,8,9.4,19.1,No,0.0,No
359,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,4.0,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [86]:
df['WindGustDir'].unique()  #for finding unique values in a column

array(['NW', 'ENE', 'SSE', 'SE', 'E', 'S', 'N', 'WNW', 'ESE', 'NE', 'NNE',
       'NNW', 'SW', 'W', 'WSW', 'SSW', nan], dtype=object)

In [87]:
len(df['WindGustDir'].unique().tolist()) #for finding number of unique values in a column

17

# loc vs iloc

In [ ]:
'''difference between iloc and loc
                iloc uses index of columns to specify them whereas loc uses name of columns
                iloc[0:5,1] gives 5 rows for 0 to 4 whereas loc[0:5,'MaxTemp'] gives 6 rows from 0 to 5
syntax- df.function[<row specification>,<column specification>] 
'''

In [88]:
#syntax- df.iloc[<row specification>,<column specification>]
df.iloc[0:6,0:4] 
df.iloc[[0,10],[1,7]]

    MaxTemp WindDir9am
0      24.3         SW
10     25.2         SE

In [89]:
#syntax simlar to iloc
df.loc[0:5,['MinTemp','MaxTemp']]

   MinTemp  MaxTemp
0      8.0     24.3
1     14.0     26.9
2     13.7     23.4
3     13.3     15.5
4      7.6     16.1
5      6.2     16.9

In [90]:
df.loc[[0,5],['MinTemp','MaxTemp']]

   MinTemp  MaxTemp
0      8.0     24.3
5      6.2     16.9

# SQL operation

In [92]:
#performing select from where operation on dataset

In [93]:
df[df['MinTemp']<15]['RainToday']

0       No
1      Yes
2      Yes
3      Yes
4      Yes
      ...
361     No
362     No
363     No
364     No
365     No
Name: RainToday, Length: 321, dtype: object

# handling missing values

In [95]:
df.isnull().any(axis=1)

0      False
1      False
2      False
3      False
4      False
       ...
361    False
362    False
363    False
364    False
365    False
Length: 366, dtype: bool

In [54]:
df=pd.read_csv('weather.csv')#reading csv file
df[df.isnull().any(axis=1)] #identifing rows containing null values

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
113,12.7,28.6,6.6,3.2,8.6,W,50.0,NaN,W,NaN,...,42,1008.3,1002.3,5,5,16.5,27.4,Yes,0.0,No
118,11.7,27.6,0.0,7.8,8.1,W,48.0,NaN,W,NaN,...,25,1013.6,1009.1,2,6,17.6,26.8,No,0.0,No
127,10.8,29.2,0.0,8.4,7.5,E,50.0,NaN,ENE,NaN,...,34,1021.6,1017.7,0,7,17.5,27.7,No,3.0,Yes
138,12.5,29.9,0.0,5.8,10.7,NW,43.0,NaN,WNW,0.0,...,30,1022.7,1018.8,0,1,16.8,29.2,No,0.0,No
140,11.5,29.3,0.0,5.2,8.0,NW,46.0,NaN,WSW,0.0,...,35,1013.8,1009.4,7,7,17.1,27.6,No,0.0,No
174,7.5,19.0,0.0,4.0,6.8,ENE,26.0,NaN,ESE,0.0,...,43,1025.5,1022.2,6,5,12.6,18.1,No,0.0,No
176,5.0,20.9,0.0,2.0,8.9,WNW,22.0,NaN,NW,0.0,...,42,1019.9,1014.3,7,6,10.1,20.6,No,0.2,No
180,-2.1,13.8,0.2,1.8,9.5,NNW,22.0,NaN,NNW,0.0,...,40,1020.6,1019.6,0,1,6.3,13.2,No,0.0,No
189,-0.2,18.1,0.0,4.4,9.4,NW,24.0,NaN,NW,0.0,...,44,1021.4,1018.9,1,1,6.7,16.9,No,0.0,No
193,9.4,19.2,0.0,2.2,7.7,NaN,24.0,E,NNW,4.0,...,47,1024.2,1020.3,7,1,12.1,18.8,No,0.0,No
195,2.2,18.6,0.0,2.0,9.2,NNW,31.0,NaN,NNW,NaN,...,44,1024.4,1021.0,1,3,8.5,17.8,No,0.0,No
200,-2.7,18.1,0.0,2.2,9.3,W,52.0,NaN,WNW,0.0,...,36,1017.8,1014.3,1,1,3.5,16.7,No,0.0,No
208,4.9,18.1,5.2,1.2,8.5,NNW,22.0,NaN,NW,0.0,...,55,1025.7,1022.3,1,1,8.9,17.7,Yes,0.0,No
209,1.4,16.8,0.0,1.6,8.2,NW,20.0,NaN,NW,0.0,...,50,1027.2,1024.7,1,4,6.2,16.3,No,0.2,No
211,-0.1,18.0,0.0,2.0,8.6,NaN,NaN,N,NNW,2.0,...,46,1033.2,1028.7,1,1,5.6,17.4,No,0.0,No
212,-0.9,18.5,0.0,2.2,8.9,E,22.0,NaN,N,0.0,...,38,1030.2,1027.4,2,3,4.7,18.2,No,0.0,No
213,0.6,14.0,0.0,2.2,2.7,NE,17.0,NaN,ENE,NaN,...,67,1032.3,1028.9,7,7,4.6,13.9,No,0.0,No
221,7.4,16.3,0.0,1.2,NaN,NNE,30.0,SSE,NE,6.0,...,65,1031.4,1027.9,7,7,12.1,14.5,No,6.2,Yes
222,8.6,13.7,6.2,2.2,0.0,NW,31.0,E,NaN,2.0,...,94,1027.8,1024.3,8,8,10.3,11.6,Yes,4.8,Yes
237,4.3,12.6,0.0,2.0,9.0,NW,46.0,NaN,WNW,0.0,...,54,1026.3,1021.9,3,1,7.8,11.3,No,0.0,No
247,-0.1,14.2,0.0,1.4,7.0,W,13.0,NaN,WNW,NaN,...,55,1032.9,1028.9,1,2,4.7,12.6,No,0.0,No
249,3.0,11.1,0.8,1.4,0.2,W,35.0,NaN,N,0.0,...,96,1024.4,1021.1,7,8,6.3,8.6,No,16.8,Yes
250,2.9,9.5,16.8,1.4,6.5,NW,35.0,NaN,NW,0.0,...,72,1021.6,1019.6,6,6,5.5,7.4,Yes,0.0,No
255,0.5,11.0,0.0,1.0,0.9,NNW,31.0,NaN,NW,0.0,...,69,1024.4,1021.9,7,7,2.8,10.7,No,0.0,No
257,-1.7,13.6,0.0,1.8,5.2,NNW,28.0,NaN,NNW,NaN,...,46,1023.0,1020.1,1,7,3.9,13.3,No,0.2,No
259,-1.8,11.5,0.0,0.6,4.7,NNW,41.0,NaN,NNW,0.0,...,55,1019.7,1013.9,7,3,1.3,11.0,No,0.0,No
262,-1.1,11.0,0.2,1.8,0.0,WNW,41.0,NaN,NE,0.0,...,87,1014.4,1009.0,7,8,2.4,8.7,No,19.2,Yes
271,0.8,12.2,0.0,1.8,8.6,NaN,NaN,S,S,19.0,...,49,1020.9,1016.8,3,1,6.5,11.2,No,0.0,No
272,-2.8,12.2,0.0,2.6,8.7,NNW,31.0,NaN,NNW,0.0,...,48,1018.3,1014.6,1,1,2.7,11.5,No,0.0,No
273,-2.8,14.1,0.0,2.2,6.8,WNW,48.0,NaN,WNW,0.0,...,38,1017.3,1012.9,1,7,3.0,12.8,No,1.0,No
278,-1.9,10.9,0.0,1.8,4.2,S,50.0,NaN,SSW,0.0,...,72,1020.8,1019.2,3,8,5.5,7.2,No,4.0,Yes
299,-1.5,17.3,0.0,2.8,9.0,NW,48.0,NaN,WNW,0.0,...,23,1023.9,1020.3,5,7,4.8,15.8,No,0.0,No
300,-3.3,15.1,0.0,3.0,NaN,SSW,30.0,SSE,SE,9.0,...,23,1027.7,1025.5,1,1,7.9,14.4,No,0.0,No
302,-0.2,16.2,0.0,3.4,5.9,E,28.0,NaN,ENE,0.0,...,45,1027.6,1022.9,7,6,7.3,14.6,No,0.0,No
312,0.2,15.5,1.0,2.4,9.4,SE,31.0,NaN,WNW,0.0,...,37,1020.6,1018.2,1,1,7.2,15.3,No,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
351,5.0,24.1,0.0,6.2,12.0,NNW,52.0,NaN,NNW,0.0,...,34,1024.5,1020.7,6,1,11.6,21.9,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No

In [ ]:
#droping values

In [51]:
df=df.dropna()  #droping rows with null values

In [52]:
df[df.isnull().any(axis=1)] #identifing rows containing null values

Empty DataFrame
Columns: [MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RISK_MM, RainTomorrow]
Index: []

[0 rows x 22 columns]

In [53]:
#filling values

In [56]:
df=pd.read_csv('weather.csv')#reading csv file
df[df.isnull().any(axis=1)] #identifing rows containing null values

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
113,12.7,28.6,6.6,3.2,8.6,W,50.0,NaN,W,NaN,...,42,1008.3,1002.3,5,5,16.5,27.4,Yes,0.0,No
118,11.7,27.6,0.0,7.8,8.1,W,48.0,NaN,W,NaN,...,25,1013.6,1009.1,2,6,17.6,26.8,No,0.0,No
127,10.8,29.2,0.0,8.4,7.5,E,50.0,NaN,ENE,NaN,...,34,1021.6,1017.7,0,7,17.5,27.7,No,3.0,Yes
138,12.5,29.9,0.0,5.8,10.7,NW,43.0,NaN,WNW,0.0,...,30,1022.7,1018.8,0,1,16.8,29.2,No,0.0,No
140,11.5,29.3,0.0,5.2,8.0,NW,46.0,NaN,WSW,0.0,...,35,1013.8,1009.4,7,7,17.1,27.6,No,0.0,No
174,7.5,19.0,0.0,4.0,6.8,ENE,26.0,NaN,ESE,0.0,...,43,1025.5,1022.2,6,5,12.6,18.1,No,0.0,No
176,5.0,20.9,0.0,2.0,8.9,WNW,22.0,NaN,NW,0.0,...,42,1019.9,1014.3,7,6,10.1,20.6,No,0.2,No
180,-2.1,13.8,0.2,1.8,9.5,NNW,22.0,NaN,NNW,0.0,...,40,1020.6,1019.6,0,1,6.3,13.2,No,0.0,No
189,-0.2,18.1,0.0,4.4,9.4,NW,24.0,NaN,NW,0.0,...,44,1021.4,1018.9,1,1,6.7,16.9,No,0.0,No
193,9.4,19.2,0.0,2.2,7.7,NaN,24.0,E,NNW,4.0,...,47,1024.2,1020.3,7,1,12.1,18.8,No,0.0,No
195,2.2,18.6,0.0,2.0,9.2,NNW,31.0,NaN,NNW,NaN,...,44,1024.4,1021.0,1,3,8.5,17.8,No,0.0,No
200,-2.7,18.1,0.0,2.2,9.3,W,52.0,NaN,WNW,0.0,...,36,1017.8,1014.3,1,1,3.5,16.7,No,0.0,No
208,4.9,18.1,5.2,1.2,8.5,NNW,22.0,NaN,NW,0.0,...,55,1025.7,1022.3,1,1,8.9,17.7,Yes,0.0,No
209,1.4,16.8,0.0,1.6,8.2,NW,20.0,NaN,NW,0.0,...,50,1027.2,1024.7,1,4,6.2,16.3,No,0.2,No
211,-0.1,18.0,0.0,2.0,8.6,NaN,NaN,N,NNW,2.0,...,46,1033.2,1028.7,1,1,5.6,17.4,No,0.0,No
212,-0.9,18.5,0.0,2.2,8.9,E,22.0,NaN,N,0.0,...,38,1030.2,1027.4,2,3,4.7,18.2,No,0.0,No
213,0.6,14.0,0.0,2.2,2.7,NE,17.0,NaN,ENE,NaN,...,67,1032.3,1028.9,7,7,4.6,13.9,No,0.0,No
221,7.4,16.3,0.0,1.2,NaN,NNE,30.0,SSE,NE,6.0,...,65,1031.4,1027.9,7,7,12.1,14.5,No,6.2,Yes
222,8.6,13.7,6.2,2.2,0.0,NW,31.0,E,NaN,2.0,...,94,1027.8,1024.3,8,8,10.3,11.6,Yes,4.8,Yes
237,4.3,12.6,0.0,2.0,9.0,NW,46.0,NaN,WNW,0.0,...,54,1026.3,1021.9,3,1,7.8,11.3,No,0.0,No
247,-0.1,14.2,0.0,1.4,7.0,W,13.0,NaN,WNW,NaN,...,55,1032.9,1028.9,1,2,4.7,12.6,No,0.0,No
249,3.0,11.1,0.8,1.4,0.2,W,35.0,NaN,N,0.0,...,96,1024.4,1021.1,7,8,6.3,8.6,No,16.8,Yes
250,2.9,9.5,16.8,1.4,6.5,NW,35.0,NaN,NW,0.0,...,72,1021.6,1019.6,6,6,5.5,7.4,Yes,0.0,No
255,0.5,11.0,0.0,1.0,0.9,NNW,31.0,NaN,NW,0.0,...,69,1024.4,1021.9,7,7,2.8,10.7,No,0.0,No
257,-1.7,13.6,0.0,1.8,5.2,NNW,28.0,NaN,NNW,NaN,...,46,1023.0,1020.1,1,7,3.9,13.3,No,0.2,No
259,-1.8,11.5,0.0,0.6,4.7,NNW,41.0,NaN,NNW,0.0,...,55,1019.7,1013.9,7,3,1.3,11.0,No,0.0,No
262,-1.1,11.0,0.2,1.8,0.0,WNW,41.0,NaN,NE,0.0,...,87,1014.4,1009.0,7,8,2.4,8.7,No,19.2,Yes
271,0.8,12.2,0.0,1.8,8.6,NaN,NaN,S,S,19.0,...,49,1020.9,1016.8,3,1,6.5,11.2,No,0.0,No
272,-2.8,12.2,0.0,2.6,8.7,NNW,31.0,NaN,NNW,0.0,...,48,1018.3,1014.6,1,1,2.7,11.5,No,0.0,No
273,-2.8,14.1,0.0,2.2,6.8,WNW,48.0,NaN,WNW,0.0,...,38,1017.3,1012.9,1,7,3.0,12.8,No,1.0,No
278,-1.9,10.9,0.0,1.8,4.2,S,50.0,NaN,SSW,0.0,...,72,1020.8,1019.2,3,8,5.5,7.2,No,4.0,Yes
299,-1.5,17.3,0.0,2.8,9.0,NW,48.0,NaN,WNW,0.0,...,23,1023.9,1020.3,5,7,4.8,15.8,No,0.0,No
300,-3.3,15.1,0.0,3.0,NaN,SSW,30.0,SSE,SE,9.0,...,23,1027.7,1025.5,1,1,7.9,14.4,No,0.0,No
302,-0.2,16.2,0.0,3.4,5.9,E,28.0,NaN,ENE,0.0,...,45,1027.6,1022.9,7,6,7.3,14.6,No,0.0,No
312,0.2,15.5,1.0,2.4,9.4,SE,31.0,NaN,WNW,0.0,...,37,1020.6,1018.2,1,1,7.2,15.3,No,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No
351,5.0,24.1,0.0,6.2,12.0,NNW,52.0,NaN,NNW,0.0,...,34,1024.5,1020.7,6,1,11.6,21.9,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No

In [59]:
df=df.fillna(0)
df[df.isnull().any(axis=1)] #identifing rows containing null values

Empty DataFrame
Columns: [MinTemp, MaxTemp, Rainfall, Evaporation, Sunshine, WindGustDir, WindGustSpeed, WindDir9am, WindDir3pm, WindSpeed9am, WindSpeed3pm, Humidity9am, Humidity3pm, Pressure9am, Pressure3pm, Cloud9am, Cloud3pm, Temp9am, Temp3pm, RainToday, RISK_MM, RainTomorrow]
Index: []

[0 rows x 22 columns]

In [68]:
df.loc[[113],['WindDir9am']]

    WindDir9am
113          0